#!/bin/sh
#
# Copyright (C) 2016-2017 Richard Mortier <mort@cantab.net>
#
# Create backups; executed from cronjob inside gitlab container

set -e

umask 0007

## builtin gitlab data backup
/opt/gitlab/bin/gitlab-rake gitlab:backup:create CRON=1

## manually backup gitlab config
tar cf /var/opt/gitlab/backups/$(date "+etc-gitlab-%s.tar") -C / etc/gitlab
tar cf /var/opt/gitlab/backups/$(date "+etc-ssh-%s.tar") -C / etc/ssh
