#!/bin/sh
#
# Copyright (C) 2017 Richard Mortier <mort@cantab.net>
#
# Extract latest backup ready to rsync to filer

set -e

cd /data/gitlab/backups

rm -rf sync
mkdir -p sync/gitlab

LATEST=$(ls -At etc-gitlab-*.tar | head -n1)
tar -x -f $LATEST -C sync -m

LATEST=$(ls -At etc-ssh-*.tar | head -n1)
tar -x -f $LATEST -C sync -m

LATEST=$(ls -At *_gitlab_backup.tar | head -n1)
tar -x -f $LATEST -C sync/gitlab -m
