#!/bin/sh
#
# Copyright (C) 2017 Richard Mortier <mort@cantab.net>
#
# Here for completeness! Runs on the cron server (receiver) to transfer tarballs
# and extract into backed up filespace.

set -e

H=svr-rmm1002-git.cl.cam.ac.uk
D=/usr/groups/netos/gitlab

rsync                                           \
      --archive                                 \
      --checksum                                \
      --compress                                \
      --delete                                  \
      --recursive                               \
      --rsh=ssh                                 \
      --times                                   \
      --verbose                                 \
    $H:/data/gitlab/backups/sync                \
    $D

chown -R rmm1002:netos $D/sync
