#!/bin/sh
#
# Copyright (C) 2017 Richard Mortier <mort@cantab.net>
#
# Here for completeness! Runs on the cron server (receiver) to transfer tarballs
# and extract into backed up filespace.

set -e

D=/usr/groups/netos/gitlab

rsync                                                   \
      --archive                                         \
      --checksum                                        \
      --compress                                        \
      --delete                                          \
      --recursive                                       \
      --rsh=ssh                                         \
      --times                                           \
      --verbose                                         \
    svr-rmm1002-git.cl.cam.ac.uk:/data/gitlab/backups/  \
    $D/tarballs

chown -R rmm1002:netos $D/tarballs

mv $D/data $D/data.old || true
mkdir -p $D/data && cd $D/data
tar -x -f $LATEST -m
rm -rf $D/data.old
