#!/usr/bin/env bash
#
# Copyright (C) 2017 Richard Mortier <mort@cantab.net>
#
# Here for completeness! Runs on the cron server (receiver) to transfer tarballs
# and extract into backed up filespace.

set -e

H=svr-rmm1002-git.cl.cam.ac.uk
S=/anfs/bigtmp/rmm1002-gitlab-sync
D=/usr/groups/netos/gitlab

SSH="ssh -p 2222 -i /home/rmm1002/.ssh/gitlabrsync-key"
SCP="scp -P 2222 -i /home/rmm1002/.ssh/gitlabrsync-key"

# generate the tarballs on the VM from the container via volume mounts
$SSH $H docker exec -i gitlab /scripts/backup

# fetch and extract the tarballs to bigtmp scratch space
umask 077
mkdir -p $S/{backups,sync/gitlab}

cd $S
$SCP $H:/data/gitlab/backups/* ./backups

tarball=$(ls -At ./backups/*_gitlab_backup.tar | head -n1)
tar -x -f $tarball -C sync/gitlab -m

tarball=$(ls -At ./backups/etc-ssh-*.tar | head -n1)
tar -x -f $tarball -C sync -m

tarball=$(ls -At ./backups/etc-gitlab-*.tar | head -n1)
tar -x -f $tarball -C sync -m

# rsync the extracted tarballs to backed up filespace
umask 002
rsync \
      --archive \
      --checksum \
      --compress \
      --delete \
      --recursive \
      --rsh="$SSH" \
      --times \
    ./sync \
    $D

chown -R rmm1002:netos $D/sync

# tidy up bigtmp and the VM
$SSH $H sudo rm /data/gitlab/backups/*.tar
