#!/bin/sh
#
# Copyright (C) 2016-2017 Richard Mortier <mort@cantab.net>
#
# Create backups and extract to ./sync subdirectory.
#
# Executed inside gitlab container from cron job on host

set -e

umask 0077

cd /var/opt/gitlab
mkdir -p sync/gitlab

## builtin gitlab data backup
/opt/gitlab/bin/gitlab-rake gitlab:backup:create CRON=1
LATEST=$(ls -At backups/*_gitlab_backup.tar | head -n1)
tar -x -f $LATEST -C sync/gitlab -m
rm $LATEST

## manually backup gitlab config
tar cf backups/$(date "+etc-gitlab-%s.tar") -C / etc/gitlab
LATEST=$(ls -At backups/etc-gitlab-*.tar | head -n1)
tar -x -f $LATEST -C sync -m
rm $LATEST

## manually backup container ssh config
tar cf backups/$(date "+etc-ssh-%s.tar") -C / etc/ssh
LATEST=$(ls -At backups/etc-ssh-*.tar | head -n1)
tar -x -f $LATEST -C sync -m
rm $LATEST

## finally, fix the permissions on everything
chown -R $HOST_UID:$HOST_GID sync
